[package]
name = "winada"
version = "0.1.11"
edition = "2021"
description = "获取Windows 本机所有适配器信息"
license = "MIT"

[dependencies]
winapi = {version = "0.3.9", features = ["iphlpapi", "winerror", "minwindef", "iptypes", "ws2def", "ws2tcpip", "in6addr", "ws2ipdef"] }
ipnet = "2.11.0"